version: "3.7"

services:

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
  #   environment:
  #     - cluster.name=elastic-demo
  #     - bootstrap.memory_lock=true
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms1512m -Xmx1512m -Des.scripting.exception_for_missing_value=true"
  #     - cluster.routing.allocation.disk.threshold_enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   # volumes:
  #   #   - ./volume/elasticsearch:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.4.2
    environment:
      - cluster.name=elastic-demo
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:

  